server:
  port: 9093
  
spring:
  application:
    name: GLOBALEXCEPTION-SERVER
  zipkin:
    base-url: http://localhost:9411
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:/9090/eureka/    
  
